[package]
name = "melt-client"
version = "0.1.21"
edition = "2021"

[dependencies]
tracing = "0.1.40"
tonic = "0.12.0"
tracing-core = "0.1.32"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
chrono = "0.4.38"
tracing-subscriber = "0.3.18"
opentelemetry-proto = "0.7.0"